In [ ]:
import numpy as np
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
Z = np.ones(10)
print(Z)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
Z = np.full(10, 5)
print(Z)

[5 5 5 5 5 5 5 5 5 5]


In [ ]:
Z = np.arange(10,51)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [ ]:
Z=np.arange(10,51,2)
print(Z) 

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [ ]:
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
Z = np.random.normal(0,1,1)
print(Z)

[-1.45702779]


In [ ]:
Z = np.random.normal(0,1,25)
print(Z)

[ 0.74429146 -0.60799858 -0.73806634  0.2420834   0.21426715 -1.13380337
  1.39457932  0.37072325 -0.42053321  0.80483331 -0.43531102 -1.03668147
 -0.17528728  0.9100065   0.42646927  0.86228684  0.21757315 -0.93264806
 -0.61290314  0.29969616  0.87799538 -1.96375221 -0.29369739  1.33992184
 -0.72494665]


In [13]:
Z=np.arange(0.01,1.01,0.01)
print(Z) 

[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13 0.14
 0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28
 0.29 0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4  0.41 0.42
 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55 0.56
 0.57 0.58 0.59 0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7
 0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8  0.81 0.82 0.83 0.84
 0.85 0.86 0.87 0.88 0.89 0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98
 0.99 1.  ]


In [15]:
mat = np.arange(1,26).reshape(5,5)
print(mat[2: ,1:])

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [16]:
mat = np.arange(1,26).reshape(5,5)
print(mat[3,4])

20


In [17]:
mat = np.arange(1,26).reshape(5,5)
print(mat[0:3,1:2])

[[ 2]
 [ 7]
 [12]]


In [18]:
mat = np.arange(1,26).reshape(5,5)
print(mat[4])

[21 22 23 24 25]


In [19]:
mat = np.arange(1,26).reshape(5,5)
print(mat[3:])

[[16 17 18 19 20]
 [21 22 23 24 25]]


In [20]:
mat = np.arange(1,26).reshape(5,5)
print(mat.sum())

325


In [21]:
mat = np.arange(1,26).reshape(5,5)
print(mat.std())

7.211102550927978


In [22]:
mat = np.arange(1,26).reshape(5,5)
print(mat.sum(axis=1))

[ 15  40  65  90 115]
